name: DragonGames
version: 4.0.0
author: matmen
website: almost-never.online

main: main.DragonGames
api-version: 1.13

commands:
  dragongames:
    description: DragonGames base command
    usage: /<command>
    aliases:
      - dg
  player:
    description: Shows player info
    usage: /<command> <player>