package me.matmen.DragonGames.enums;

import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.jetbrains.annotations.Contract;

public enum Enchantments {
    WOODEN_SWORD_DAMAGE_ALL(Material.WOODEN_SWORD, Enchantment.DAMAGE_ALL, 5),
    WOODEN_SWORD_KNOCKBACK(Material.WOODEN_SWORD, Enchantment.KNOCKBACK, 2),
    WOODEN_SWORD_FIRE_ASPECT(Material.WOODEN_SWORD, Enchantment.FIRE_ASPECT, 2),

    STONE_SWORD_DAMAGE_ALL(Material.STONE_SWORD, Enchantment.DAMAGE_ALL, 5),
    STONE_SWORD_KNOCKBACK(Material.STONE_SWORD, Enchantment.KNOCKBACK, 2),
    STONE_SWORD_FIRE_ASPECT(Material.STONE_SWORD, Enchantment.FIRE_ASPECT, 2),

    IRON_SWORD_DAMAGE_ALL(Material.IRON_SWORD, Enchantment.DAMAGE_ALL, 5),
    IRON_SWORD_KNOCKBACK(Material.IRON_SWORD, Enchantment.KNOCKBACK, 2),
    IRON_SWORD_FIRE_ASPECT(Material.IRON_SWORD, Enchantment.FIRE_ASPECT, 2),

    DIAMOND_AXE_DAMAGE_ALL(Material.DIAMOND_AXE, Enchantment.DAMAGE_ALL, 5),
    DIAMOND_AXE_LOOT_BONUS_BLOCKS(Material.DIAMOND_AXE, Enchantment.LOOT_BONUS_BLOCKS, 3),
    DIAMOND_AXE_DIG_SPEED(Material.DIAMOND_AXE, Enchantment.DIG_SPEED, 5),

    DIAMOND_SWORD_DAMAGE_ALL(Material.DIAMOND_SWORD, Enchantment.DAMAGE_ALL, 5),
    DIAMOND_SWORD_KNOCKBACK(Material.DIAMOND_SWORD, Enchantment.KNOCKBACK, 2),
    DIAMOND_SWORD_FIRE_ASPECT(Material.DIAMOND_SWORD, Enchantment.FIRE_ASPECT, 2),

    BOW_ARROW_FIRE(Material.BOW, Enchantment.ARROW_FIRE, 1),
    BOW_ARROW_KNOCKBACK(Material.BOW, Enchantment.ARROW_KNOCKBACK, 2),
    BOW_ARROW_DAMAGE(Material.BOW, Enchantment.ARROW_DAMAGE, 5),

    CROSSBOW_MULTISHOT(Material.CROSSBOW, Enchantment.MULTISHOT, 1),
    CROSSBOW_PIERCING(Material.CROSSBOW, Enchantment.PIERCING, 4),
    CROSSBOW_QUICK_CHARGE(Material.CROSSBOW, Enchantment.QUICK_CHARGE, 3),

    TRIDENT_LOYALTY(Material.TRIDENT, Enchantment.LOYALTY, 3),
    TRIDENT_CHANNELING(Material.TRIDENT, Enchantment.CHANNELING, 1),

    DIAMOND_HELMET_PROTECTION_FIRE(Material.DIAMOND_HELMET, Enchantment.PROTECTION_FIRE, 4),
    DIAMOND_HELMET_PROTECTION_ENVIRONMENTAL(Material.DIAMOND_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    DIAMOND_HELMET_PROTECTION_EXPLOSIONS(Material.DIAMOND_HELMET, Enchantment.PROTECTION_EXPLOSIONS, 4),
    DIAMOND_HELMET_THORNS(Material.DIAMOND_HELMET, Enchantment.THORNS, 3),
    DIAMOND_HELMET_PROTECTION_PROJECTILE(Material.DIAMOND_HELMET, Enchantment.PROTECTION_PROJECTILE, 4),

    DIAMOND_CHESTPLATE_PROTECTION_FIRE(Material.DIAMOND_CHESTPLATE, Enchantment.PROTECTION_FIRE, 4),
    DIAMOND_CHESTPLATE_PROTECTION_ENVIRONMENTAL(Material.DIAMOND_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    DIAMOND_CHESTPLATE_PROTECTION_EXPLOSIONS(Material.DIAMOND_CHESTPLATE, Enchantment.PROTECTION_EXPLOSIONS, 4),
    DIAMOND_CHESTPLATE_THORNS(Material.DIAMOND_CHESTPLATE, Enchantment.THORNS, 3),
    DIAMOND_CHESTPLATE_PROTECTION_PROJECTILE(Material.DIAMOND_CHESTPLATE, Enchantment.PROTECTION_PROJECTILE, 4),

    DIAMOND_LEGGINGS_PROTECTION_FIRE(Material.DIAMOND_LEGGINGS, Enchantment.PROTECTION_FIRE, 4),
    DIAMOND_LEGGINGS_PROTECTION_ENVIRONMENTAL(Material.DIAMOND_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    DIAMOND_LEGGINGS_PROTECTION_EXPLOSIONS(Material.DIAMOND_LEGGINGS, Enchantment.PROTECTION_EXPLOSIONS, 4),
    DIAMOND_LEGGINGS_THORNS(Material.DIAMOND_LEGGINGS, Enchantment.THORNS, 3),
    DIAMOND_LEGGINGS_PROTECTION_PROJECTILE(Material.DIAMOND_LEGGINGS, Enchantment.PROTECTION_PROJECTILE, 4),

    DIAMOND_BOOTS_PROTECTION_FIRE(Material.DIAMOND_BOOTS, Enchantment.PROTECTION_FIRE, 4),
    DIAMOND_BOOTS_PROTECTION_ENVIRONMENTAL(Material.DIAMOND_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    DIAMOND_BOOTS_PROTECTION_EXPLOSIONS(Material.DIAMOND_BOOTS, Enchantment.PROTECTION_EXPLOSIONS, 4),
    DIAMOND_BOOTS_THORNS(Material.DIAMOND_BOOTS, Enchantment.THORNS, 3),
    DIAMOND_BOOTS_PROTECTION_PROJECTILE(Material.DIAMOND_BOOTS, Enchantment.PROTECTION_PROJECTILE, 4),
    DIAMOND_BOOTS_PROTECTION_FALL(Material.DIAMOND_BOOTS, Enchantment.PROTECTION_FALL, 4),

    IRON_HELMET_PROTECTION_FIRE(Material.IRON_HELMET, Enchantment.PROTECTION_FIRE, 4),
    IRON_HELMET_PROTECTION_ENVIRONMENTAL(Material.IRON_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    IRON_HELMET_PROTECTION_EXPLOSIONS(Material.IRON_HELMET, Enchantment.PROTECTION_EXPLOSIONS, 4),
    IRON_HELMET_THORNS(Material.IRON_HELMET, Enchantment.THORNS, 3),
    IRON_HELMET_PROTECTION_PROJECTILE(Material.IRON_HELMET, Enchantment.PROTECTION_PROJECTILE, 4),

    IRON_CHESTPLATE_PROTECTION_FIRE(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_FIRE, 4),
    IRON_CHESTPLATE_PROTECTION_ENVIRONMENTAL(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    IRON_CHESTPLATE_PROTECTION_EXPLOSIONS(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_EXPLOSIONS, 4),
    IRON_CHESTPLATE_THORNS(Material.IRON_CHESTPLATE, Enchantment.THORNS, 3),
    IRON_CHESTPLATE_PROTECTION_PROJECTILE(Material.IRON_CHESTPLATE, Enchantment.PROTECTION_PROJECTILE, 4),

    IRON_LEGGINGS_PROTECTION_FIRE(Material.IRON_LEGGINGS, Enchantment.PROTECTION_FIRE, 4),
    IRON_LEGGINGS_PROTECTION_ENVIRONMENTAL(Material.IRON_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    IRON_LEGGINGS_PROTECTION_EXPLOSIONS(Material.IRON_LEGGINGS, Enchantment.PROTECTION_EXPLOSIONS, 4),
    IRON_LEGGINGS_THORNS(Material.IRON_LEGGINGS, Enchantment.THORNS, 3),
    IRON_LEGGINGS_PROTECTION_PROJECTILE(Material.IRON_LEGGINGS, Enchantment.PROTECTION_PROJECTILE, 4),

    IRON_BOOTS_PROTECTION_FIRE(Material.IRON_BOOTS, Enchantment.PROTECTION_FIRE, 4),
    IRON_BOOTS_PROTECTION_ENVIRONMENTAL(Material.IRON_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    IRON_BOOTS_PROTECTION_EXPLOSIONS(Material.IRON_BOOTS, Enchantment.PROTECTION_EXPLOSIONS, 4),
    IRON_BOOTS_THORNS(Material.IRON_BOOTS, Enchantment.THORNS, 3),
    IRON_BOOTS_PROTECTION_PROJECTILE(Material.IRON_BOOTS, Enchantment.PROTECTION_PROJECTILE, 4),
    IRON_BOOTS_PROTECTION_FALL(Material.IRON_BOOTS, Enchantment.PROTECTION_FALL, 4),

    GOLDEN_HELMET_PROTECTION_FIRE(Material.GOLDEN_HELMET, Enchantment.PROTECTION_FIRE, 4),
    GOLDEN_HELMET_PROTECTION_ENVIRONMENTAL(Material.GOLDEN_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    GOLDEN_HELMET_PROTECTION_EXPLOSIONS(Material.GOLDEN_HELMET, Enchantment.PROTECTION_EXPLOSIONS, 4),
    GOLDEN_HELMET_THORNS(Material.GOLDEN_HELMET, Enchantment.THORNS, 3),
    GOLDEN_HELMET_PROTECTION_PROJECTILE(Material.GOLDEN_HELMET, Enchantment.PROTECTION_PROJECTILE, 4),

    GOLDEN_CHESTPLATE_PROTECTION_FIRE(Material.GOLDEN_CHESTPLATE, Enchantment.PROTECTION_FIRE, 4),
    GOLDEN_CHESTPLATE_PROTECTION_ENVIRONMENTAL(Material.GOLDEN_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    GOLDEN_CHESTPLATE_PROTECTION_EXPLOSIONS(Material.GOLDEN_CHESTPLATE, Enchantment.PROTECTION_EXPLOSIONS, 4),
    GOLDEN_CHESTPLATE_THORNS(Material.GOLDEN_CHESTPLATE, Enchantment.THORNS, 3),
    GOLDEN_CHESTPLATE_PROTECTION_PROJECTILE(Material.GOLDEN_CHESTPLATE, Enchantment.PROTECTION_PROJECTILE, 4),

    GOLDEN_LEGGINGS_PROTECTION_FIRE(Material.GOLDEN_LEGGINGS, Enchantment.PROTECTION_FIRE, 4),
    GOLDEN_LEGGINGS_PROTECTION_ENVIRONMENTAL(Material.GOLDEN_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    GOLDEN_LEGGINGS_PROTECTION_EXPLOSIONS(Material.GOLDEN_LEGGINGS, Enchantment.PROTECTION_EXPLOSIONS, 4),
    GOLDEN_LEGGINGS_THORNS(Material.GOLDEN_LEGGINGS, Enchantment.THORNS, 3),
    GOLDEN_LEGGINGS_PROTECTION_PROJECTILE(Material.GOLDEN_LEGGINGS, Enchantment.PROTECTION_PROJECTILE, 4),

    GOLDEN_BOOTS_PROTECTION_FIRE(Material.GOLDEN_BOOTS, Enchantment.PROTECTION_FIRE, 4),
    GOLDEN_BOOTS_PROTECTION_ENVIRONMENTAL(Material.GOLDEN_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    GOLDEN_BOOTS_PROTECTION_EXPLOSIONS(Material.GOLDEN_BOOTS, Enchantment.PROTECTION_EXPLOSIONS, 4),
    GOLDEN_BOOTS_THORNS(Material.GOLDEN_BOOTS, Enchantment.THORNS, 3),
    GOLDEN_BOOTS_PROTECTION_PROJECTILE(Material.GOLDEN_BOOTS, Enchantment.PROTECTION_PROJECTILE, 4),
    GOLDEN_BOOTS_PROTECTION_FALL(Material.GOLDEN_BOOTS, Enchantment.PROTECTION_FALL, 4),

    LEATHER_HELMET_PROTECTION_FIRE(Material.LEATHER_HELMET, Enchantment.PROTECTION_FIRE, 4),
    LEATHER_HELMET_PROTECTION_ENVIRONMENTAL(Material.LEATHER_HELMET, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    LEATHER_HELMET_PROTECTION_EXPLOSIONS(Material.LEATHER_HELMET, Enchantment.PROTECTION_EXPLOSIONS, 4),
    LEATHER_HELMET_THORNS(Material.LEATHER_HELMET, Enchantment.THORNS, 3),
    LEATHER_HELMET_PROTECTION_PROJECTILE(Material.LEATHER_HELMET, Enchantment.PROTECTION_PROJECTILE, 4),

    LEATHER_CHESTPLATE_PROTECTION_FIRE(Material.LEATHER_CHESTPLATE, Enchantment.PROTECTION_FIRE, 4),
    LEATHER_CHESTPLATE_PROTECTION_ENVIRONMENTAL(Material.LEATHER_CHESTPLATE, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    LEATHER_CHESTPLATE_PROTECTION_EXPLOSIONS(Material.LEATHER_CHESTPLATE, Enchantment.PROTECTION_EXPLOSIONS, 4),
    LEATHER_CHESTPLATE_THORNS(Material.LEATHER_CHESTPLATE, Enchantment.THORNS, 3),
    LEATHER_CHESTPLATE_PROTECTION_PROJECTILE(Material.LEATHER_CHESTPLATE, Enchantment.PROTECTION_PROJECTILE, 4),

    LEATHER_LEGGINGS_PROTECTION_FIRE(Material.LEATHER_LEGGINGS, Enchantment.PROTECTION_FIRE, 4),
    LEATHER_LEGGINGS_PROTECTION_ENVIRONMENTAL(Material.LEATHER_LEGGINGS, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    LEATHER_LEGGINGS_PROTECTION_EXPLOSIONS(Material.LEATHER_LEGGINGS, Enchantment.PROTECTION_EXPLOSIONS, 4),
    LEATHER_LEGGINGS_THORNS(Material.LEATHER_LEGGINGS, Enchantment.THORNS, 3),
    LEATHER_LEGGINGS_PROTECTION_PROJECTILE(Material.LEATHER_LEGGINGS, Enchantment.PROTECTION_PROJECTILE, 4),

    LEATHER_BOOTS_PROTECTION_FIRE(Material.LEATHER_BOOTS, Enchantment.PROTECTION_FIRE, 4),
    LEATHER_BOOTS_PROTECTION_ENVIRONMENTAL(Material.LEATHER_BOOTS, Enchantment.PROTECTION_ENVIRONMENTAL, 4),
    LEATHER_BOOTS_PROTECTION_EXPLOSIONS(Material.LEATHER_BOOTS, Enchantment.PROTECTION_EXPLOSIONS, 4),
    LEATHER_BOOTS_THORNS(Material.LEATHER_BOOTS, Enchantment.THORNS, 3),
    LEATHER_BOOTS_PROTECTION_PROJECTILE(Material.LEATHER_BOOTS, Enchantment.PROTECTION_PROJECTILE, 4),
    LEATHER_BOOTS_PROTECTION_FALL(Material.LEATHER_BOOTS, Enchantment.PROTECTION_FALL, 4),

    WOODEN_PICKAXE_LOOT_BONUS_BLOCKS(Material.WOODEN_PICKAXE, Enchantment.LOOT_BONUS_BLOCKS, 3),
    WOODEN_PICKAXE_DIG_SPEED(Material.WOODEN_PICKAXE, Enchantment.DIG_SPEED, 5),

    GOLDEN_PICKAXE_LOOT_BONUS_BLOCKS(Material.GOLDEN_PICKAXE, Enchantment.LOOT_BONUS_BLOCKS, 3),
    GOLDEN_PICKAXE_DIG_SPEED(Material.GOLDEN_PICKAXE, Enchantment.DIG_SPEED, 5),

    IRON_PICKAXE_LOOT_BONUS_BLOCKS(Material.IRON_PICKAXE, Enchantment.LOOT_BONUS_BLOCKS, 3),
    IRON_PICKAXE_DIG_SPEED(Material.IRON_PICKAXE, Enchantment.DIG_SPEED, 5),

    DIAMOND_PICKAXE_LOOT_BONUS_BLOCKS(Material.DIAMOND_PICKAXE, Enchantment.LOOT_BONUS_BLOCKS, 3),
    DIAMOND_PICKAXE_DIG_SPEED(Material.DIAMOND_PICKAXE, Enchantment.DIG_SPEED, 5),

    WOODEN_SHOVEL_LOOT_BONUS_BLOCKS(Material.WOODEN_SHOVEL, Enchantment.LOOT_BONUS_BLOCKS, 3),
    WOODEN_SHOVEL_DIG_SPEED(Material.WOODEN_SHOVEL, Enchantment.DIG_SPEED, 5),

    GOLDEN_SHOVEL_LOOT_BONUS_BLOCKS(Material.GOLDEN_SHOVEL, Enchantment.LOOT_BONUS_BLOCKS, 3),
    GOLDEN_SHOVEL_DIG_SPEED(Material.GOLDEN_SHOVEL, Enchantment.DIG_SPEED, 5),

    IRON_SHOVEL_LOOT_BONUS_BLOCKS(Material.IRON_SHOVEL, Enchantment.LOOT_BONUS_BLOCKS, 3),
    IRON_SHOVEL_DIG_SPEED(Material.IRON_SHOVEL, Enchantment.DIG_SPEED, 5),

    DIAMOND_SHOVEL_LOOT_BONUS_BLOCKS(Material.DIAMOND_SHOVEL, Enchantment.LOOT_BONUS_BLOCKS, 3),
    DIAMOND_SHOVEL_DIG_SPEED(Material.DIAMOND_SHOVEL, Enchantment.DIG_SPEED, 5);

    public final Material type;
    public final Enchantment enchantment;
    public final int maxLevel;

    @Contract(pure = true)
    Enchantments(Material itemType, Enchantment enchantment, int maxLevel) {
        this.type = itemType;
        this.enchantment = enchantment;
        this.maxLevel = maxLevel;
    }
}
